services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    hostname: umanager_backend
    container_name: umanager_backend
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./:/home/app
    

  db:
    image: postgres:14.3-alpine
    hostname: umanager_db
    container_name: umanager_db
    restart: on-failure
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db-postgres:/var/lib/postgresql/data
    

volumes:
  db-postgres:

