  #version: '3.8'
#
#services:
#  web:
#    container_name : umanager_backend
#    depends_on:
#      - db
#    build: .
#    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0'
#    volumes:
#      - .:/app
#    ports:
#      - 8008:8000
#    env_file:
#      - .env
#  db:
#    image: postgres:15-alpine
#    hostname: db_postgres
#    container_name: umanager_db
#    restart: on-failure
#    volumes:
#      - app-db-data:/var/lib/postgresql/data/pgdata
#    env_file:
#      - .env
#    environment:
#      - PGDATA=/var/lib/postgresql/data/pgdata
#
#volumes:
#  app-db-data:


version: "3.9"

services:
  backend:
    build:
      context: ./
      dockerfile: Dockerfile
    hostname: umanager_backend
    container_name: umanager_backend
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./:/home/app
    

  db:
    image: postgres:14.3-alpine
    hostname: umanager_db
    container_name: umanager_db
    restart: on-failure
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db-postgres:/var/lib/postgresql/data
    

volumes:
  db-postgres:

