"""empty message

Revision ID: 10b0304c4fbc
Revises: 9c26b3d0b442
Create Date: 2023-09-13 00:51:39.313785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10b0304c4fbc'
down_revision: Union[str, None] = '9c26b3d0b442'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_role_name', table_name='role')
    op.create_index(op.f('ix_role_name'), 'role', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_role_name'), table_name='role')
    op.create_index('ix_role_name', 'role', ['name'], unique=False)
    # ### end Alembic commands ###
