"""empty message

Revision ID: 325b61fec4fb
Revises: d0c3bf80a159
Create Date: 2023-09-26 13:23:05.813598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '325b61fec4fb'
down_revision: Union[str, None] = 'd0c3bf80a159'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('auth_identity_provider', sa.String(length=255), nullable=True))
    op.drop_column('user', 'auth_identity_provided')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('auth_identity_provided', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('user', 'auth_identity_provider')
    # ### end Alembic commands ###
