"""empty message

Revision ID: 0f5889908d7e
Revises: 5925969227ee
Create Date: 2023-09-22 01:21:38.120868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f5889908d7e'
down_revision: Union[str, None] = '5925969227ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('user', sa.Column('profile_img', sa.String(), nullable=True))
    op.add_column('user', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('auth_identity_provided', sa.String(length=255), nullable=True))
    op.add_column('user', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('user', 'last_login')
    op.drop_column('user', 'auth_identity_provided')
    op.drop_column('user', 'email_verified')
    op.drop_column('user', 'profile_img')
    op.drop_column('user', 'phone_number')
    # ### end Alembic commands ###
