"""empty message

Revision ID: 9c26b3d0b442
Revises: 94589a3f09fa
Create Date: 2023-09-13 00:24:09.421388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c26b3d0b442'
down_revision: Union[str, None] = '94589a3f09fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups_role_membership',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'role_id')
    )
    op.drop_table('groups_membership')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups_membership',
    sa.Column('group_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], name='groups_membership_group_id_fkey'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name='groups_membership_role_id_fkey'),
    sa.PrimaryKeyConstraint('group_id', 'role_id', name='groups_membership_pkey')
    )
    op.drop_table('groups_role_membership')
    # ### end Alembic commands ###
